#!/bin/bash
country=ID
state=Bandung
locality=JawaBarat
organization=fas
organizationalunit=fas
commonname=faried
email=admin@fas.com

ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

rm /usr/local/etc/config.yml
rm /etc/stunnel/stunnel.conf
rm /etc/stunnel/stunnel.pem
rm /etc/systemd/system/ws.service

echo "============= SETTING PORT ============"
sleep 0.5
read -p "Port SSH Dropbear : " ssh
read -p "Port DEFAULT : " de
read -p "Port STUNNEL : " ssl

echo "Procesing to server..."
sleep 0.5

echo "=============== INSTALL STUNNEL4 ==============="
apt-get install stunnel4 -y
clear

cat > /etc/stunnel/stunnel.conf <<-END
pid = /var/run/stunnel.pid
cert = /etc/stunnel/stunnel.pem
client = no
socket = a:SO_REUSEADDR=1
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
[https]
accept = :::$ssl
connect = 127.0.0.1:9990

END

clear

echo "=============== INSTALL SERTIFIKAT ==============="
openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 1095 \
						-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"
cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
chmod 600 /etc/stunnel/stunnel.pem

cat > /etc/systemd/system/nodews.service <<-END
[Unit]
Description=fas-ws
After=network.target nss-lookup.target

[Service]
User=root
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/ws-epro -salome -listen :9990 -ssh 127.0.0.1:$ssh -default 127.0.0.1:$de -f /usr/local/etc/config.yml
Restart=on-failure
RestartPreventExitStatus=1

[Install]
WantedBy=multi-user.target

END
chmod +x /etc/systemd/system/nodews.service

mkdir /etc/fas/
wget -O /etc/fas/fas.net https://raw.githubusercontent.com/gozhien/apa/main/fas.net

echo "=============== INSTALL DROPBEAR ==============="
apt-get install dropbear -y
rm /etc/default/dropbear
cat > /etc/default/dropbear <<-END
NO_START=0
DROPBEAR_PORT=$ssh
DROPBEAR_EXTRA_ARGS=
DROPBEAR_BANNER="/etc/fas/fas.net"
DROPBEAR_RECEIVE_WINDOW=65536
END

wget -O /usr/local/bin/ws-epro https://github.com/gozhien/apa/raw/main/ws-epro
chmod +x /usr/local/bin/ws-epro

cat > /usr/local/etc/config.yml <<-END
# verbose level 0=info, 1=verbose, 2=very verbose
verbose: 0
listen:
  # salome
    - target_host: 127.0.0.1
    target_port: 9990
    listen_port: $de
END
chmod +x /usr/local/etc/config.yml

##restart
#echo "0 */6 * * * /usr/bin/cah" >> /etc/cron.d/cache

wget -O /usr/bin/x https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/x
chmod +x /usr/bin/x

##starting
service dropbear restart
systemctl enable nodews
systemctl start nodews
service stunnel4 start
clear

echo "Configuration to server..."
sleep 0.3
clear
LP='\033[1;35m'
NC='\033[0m' # No Color
echo -e "${LP}"
echo    "=========== Detail PORT ============"
echo    "---------------------------------------"
echo    "   WS  NON SSL : $de"
echo    "   VPN : $ssh"
echo    "   SSL : $ssl"
echo    "---------------------------------------"
echo    ""
echo -e "${NC}"
rm -rf cert.pem key.pem epro
