#!/bin/bash
country=ID
state=Bandung
locality=JawaBarat
organization=fas
organizationalunit=fas
commonname=faried
email=admin@fas.com

cd

# set time GMT +7 jakarta
#rm /etc/localtime
#ln -s /usr/share/zoneinfo/posix/Asia/Jakarta /etc/localtime

echo "=============== INSTALL UNTUK BUAT SSH ==============="
wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1unjHNf7PhWzq599fwoqY2g0PMnh4IkOz' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1unjHNf7PhWzq599fwoqY2g0PMnh4IkOz" -O /usr/bin/cek && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/cek

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1xltcIu-fdRiIofum6DQhD-dBgx1MGIOM' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xltcIu-fdRiIofum6DQhD-dBgx1MGIOM" -O /usr/bin/hapus && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/hapus

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1u4iRy52uBtrQ715wI3qC51bSDyzIgqaS' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1u4iRy52uBtrQ715wI3qC51bSDyzIgqaS" -O /usr/bin/list && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/list

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=10kp8lvRN_mFfHDF51Oh2ME58JvrWEl2a' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=10kp8lvRN_mFfHDF51Oh2ME58JvrWEl2a" -O /usr/bin/new && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/new

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=d/1FUSVykTzJVHmEJgHvgTFrF1Tfa9j6tQu' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=d/1FUSVykTzJVHmEJgHvgTFrF1Tfa9j6tQu" -O /usr/bin/trial && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/trial
clear

echo "=============== INSTALL STUNNEL4 ==============="
apt-get install stunnel4 -y
rm /etc/stunnel/stunnel.conf
cat > /etc/stunnel/stunnel.conf <<-END
pid = /var/run/stunnel.pid
cert = /etc/stunnel/stunnel.pem
client = no
socket = a:SO_REUSEADDR=1
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
[https]
accept = :::443
connect = :::80

END

echo "=============== INSTALL SERTIFIKAT ==============="
rm /etc/stunnel/stunnel.pem
openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 1095 \
					-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"
cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
clear

echo "=============== INSTALL DROPBEAR ==============="
apt-get install dropbear -y
rm /etc/default/dropbear
cat > /etc/default/dropbear <<-END
NO_START=0
DROPBEAR_PORT=2222

DROPBEAR_EXTRA_ARGS=

DROPBEAR_BANNER="/root/fas.net"

DROPBEAR_RECEIVE_WINDOW=65536
END

echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1wEJXcpz7LJNAELhrxNwlHmxVAaWEXowH' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1wEJXcpz7LJNAELhrxNwlHmxVAaWEXowH" -O fas.net && rm -rf /tmp/cookies.txt
chmod +x fas.net
clear

#echo "=============== INSTALL BADVPN ==============="
#apt -y install unzip && apt -y install cmake && apt -y install make
#wget https://github.com/ambrop72/badvpn/archive/master.zip && unzip master.zip && cd badvpn-master && mkdir build && cd build && cmake .. -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 && make install

#wget -O /etc/systemd/system/badvpn.service https://gitlab.com/PANCHO7532/scripts-and-random-code/-/raw/master/nfree/badvpn.service && chmod +x /etc/systemd/system/badvpn.service
#systemctl enable badvpn
#systemctl start badvpn

echo "=============== INSTALL WS ==============="

mkdir /etc/fas
wget -O /etc/fas/pd.py https://raw.githubusercontent.com/gozhien/apa/main/sh.py
clear

apt -y install python
cat > /etc/systemd/system/nodews.service <<-END
[Unit]
Description=fas-nodews
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=python /etc/fas/sh.py 80
Restart=on-failure
RestartPreventExitStatus=1

[Install]
WantedBy=multi-user.target
END
clear

wget -O /usr/bin/x https://raw.githubusercontent.com/gozhien/apa/main/x
chmod +x /usr/bin/x
clear

echo "=============== MENJALANKAN SEMUA ==============="
cd $home
#apt -y autoremove unzip zip make cmake
#rm -rf badvpn-master master.zip
systemctl enable nodews
systemctl start nodews
x
rm -rf key.pem cert.pem shws
/etc/init.d/dropbear restart
/etc/init.d/stunnel4 restart
clear
