#!/bin/bash
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --without-logfiles
mkdir /etc/xray
wget -O /etc/xray/xray.key https://github.com/gozhien/ih_apa_ya/raw/main/ozip.key
wget -O /etc/xray/xray.crt https://github.com/gozhien/ih_apa_ya/raw/main/ozip.crt

clear

rm /usr/local/etc/xray/config.json
cat > /usr/local/etc/xray/config.json <<-END
{
    "log": {
        "loglevel": "none"
    },
    "routing": {
        "domainStrategy": "AsIs"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 80,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "e3444bdd-fbd6-47e6-99c6-b3ce86910a3b"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
            "wsSettings": {
            "path": "/worryfree"
               }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
END
iptables -I INPUT -p tcp --dport 80 -j ACCEPT && iptables-save > /etc/iptables/rules.v4
rm ok
service xray restart
clear