#!/bin/bash

#==========TANGGAL DIBUAT===========
#12/15/2021
#21:37:34 WIB
#==========TANGGAL DIBUAT===========

#ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

curl -O https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
chmod 755 openvpn-install.sh
./openvpn-install.sh
clear

echo "=============== INSTALL WS ==============="

mkdir /etc/fas
wget -O /etc/fas/proxy3.js https://raw.githubusercontent.com/gozhien/apa/main/proxy3.js && cd $home
clear

apt -y install nodejs
cat > /etc/systemd/system/nodews.service <<-END
[Unit]
Description=fas-nodews
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=node /etc/fas/proxy3.js -dhost 127.0.0.1 -dport 1194 -mport 80 -skip 2
Restart=on-failure
RestartPreventExitStatus=1

[Install]
WantedBy=multi-user.target
END

cat > /etc/systemd/system/wsssl.service <<-END
[Unit]
Description=fas-wsssl
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=node /etc/fas/proxy3.js -dhost 127.0.0.1 -dport 1194 -mport 443 -skip 2
Restart=on-failure
RestartPreventExitStatus=1

[Install]
WantedBy=multi-user.target
END

chmod +x /etc/systemd/system/wsssl.service
clear

wget -O /usr/bin/x https://raw.githubusercontent.com/gozhien/apa/main/x
chmod +x /usr/bin/x

rm -rf vpn auto
bash x
clear
