#!/bin/bash
country=ID
state=Bandung
locality=JawaBarat
organization=fas
organizationalunit=fas
commonname=faried
email=admin@fas.com

cd

# set time GMT +7 jakarta
#rm /etc/localtime
#ln -s /usr/share/zoneinfo/posix/Asia/Jakarta /etc/localtime

#echo "=============== INSTALL UNTUK BUAT SSH ==============="
#wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1unjHNf7PhWzq599fwoqY2g0PMnh4IkOz' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1unjHNf7PhWzq599fwoqY2g0PMnh4IkOz" -O /usr/bin/cek && rm -rf /tmp/cookies.txt
#chmod +x /usr/bin/cek

#wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1xltcIu-fdRiIofum6DQhD-dBgx1MGIOM' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xltcIu-fdRiIofum6DQhD-dBgx1MGIOM" -O /usr/bin/hapus && rm -rf /tmp/cookies.txt
#chmod +x /usr/bin/hapus

#wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1u4iRy52uBtrQ715wI3qC51bSDyzIgqaS' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1u4iRy52uBtrQ715wI3qC51bSDyzIgqaS" -O /usr/bin/list && rm -rf /tmp/cookies.txt
#chmod +x /usr/bin/list

#wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=10kp8lvRN_mFfHDF51Oh2ME58JvrWEl2a' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=10kp8lvRN_mFfHDF51Oh2ME58JvrWEl2a" -O /usr/bin/new && rm -rf /tmp/cookies.txt
#chmod +x /usr/bin/new

#wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=d/1FUSVykTzJVHmEJgHvgTFrF1Tfa9j6tQu' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=d/1FUSVykTzJVHmEJgHvgTFrF1Tfa9j6tQu" -O /usr/bin/trial && rm -rf /tmp/cookies.txt
#chmod +x /usr/bin/trial
#clear

apt-get install certbot -y && apt-get install gcc g++ build-essential libreadline-dev zlib1g-dev libssl-dev unzip -y && wget -q -O stunnel5.zip "https://github.com/fisabiliyusri/Mantap/raw/main/stunnel5/stunnel5.zip" && unzip -o stunnel5.zip && cd /root/stunnel && chmod +x configure && ./configure && make && make install && cd /root && rm -r -f stunnel && rm -f stunnel5.zip && mkdir -p /etc/stunnel5 && chmod 644 /etc/stunnel5

# Download Config Stunnel5
cat > /etc/stunnel5/stunnel5.conf <<-END
cert = /etc/stunnel5/stunnel.pem
client = no
socket = a:SO_REUSEADDR=1
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

[dropbear]
accept = :::443
connect = :::80
END

# Service Stunnel5 systemctl restart stunnel5
cat > /etc/systemd/system/stunnel5.service << END
[Unit]
Description=Stunnel5 Service
Documentation=https://stunnel.org
Documentation=https://github.com/Akbar218
After=syslog.target network-online.target

[Service]
ExecStart=/usr/local/bin/stunnel5 /etc/stunnel5/stunnel5.conf
Type=forking

[Install]
WantedBy=multi-user.target
END

# Service Stunnel5 /etc/init.d/stunnel5
wget -q -O /etc/init.d/stunnel5 "https://raw.githubusercontent.com/fisabiliyusri/Mantap/main/stunnel5/stunnel5.init"

openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 1095 \
					-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"
cat key.pem cert.pem >> /etc/stunnel5/stunnel.pem

# Ubah Izin Akses
chmod 600 /etc/stunnel5/stunnel5.pem
chmod +x /etc/init.d/stunnel5
cp /usr/local/bin/stunnel /usr/local/bin/stunnel5
clear

echo "=============== INSTALL DROPBEAR ==============="
apt-get install dropbear -y
rm /etc/default/dropbear
cat > /etc/default/dropbear <<-END
NO_START=0
DROPBEAR_PORT=222
DROPBEAR_EXTRA_ARGS=
DROPBEAR_BANNER="/etc/fas/fas.net"
DROPBEAR_RECEIVE_WINDOW=65536
END

#echo "/bin/false" >> /etc/shells
#echo "/usr/sbin/nologin" >> /etc/shells
#clear

echo "=============== INSTALL WS ==============="

mkdir /etc/fas
wget -O /etc/fas/sh.js https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/proxy3.js
wget -O /etc/fas/fas.net https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/fas.net
chmod +x /etc/fas/fas.net
chmod +x /etc/fas/sh.js
clear

apt -y install nodejs
rm -rf /etc/systemd/system/nodews.service
cat > /etc/systemd/system/nodews.service <<-END
[Unit]
Description=fas-wsssl
After=network.target nss-lookup.target
[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=node /etc/fas/sh.js -dhost 127.0.0.1 -dport 222 -mport 80 -skip 1
Restart=on-failure
RestartPreventExitStatus=1
[Install]
WantedBy=multi-user.target
END
clear

wget -O /usr/bin/x https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/x
chmod +x /usr/bin/x
clear

#echo "=============== INSTALL BADVPN ==============="
#apt -y install cmake && apt -y install make && wget https://github.com/gozhien/apa/raw/main/apa.tar.bz2 && tar xf apa.tar.bz2 && cd badvpn && mkdir build && cd build && cmake .. -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 -DBUILD_TUN2SOCKS=1 && make install && rm -rf badvpn apa.tar.bz2 && apt --purge autoremove make cmake -y && wget -O /etc/systemd/system/bad.service https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/bad.service && chmod +x /etc/systemd/system/bad.service && systemctl enable bad && systemctl start bad && cd

echo "=============== MENJALANKAN SEMUA ==============="
apt-get autoremove --purge install certbot -y
apt-get autoremove --purge gcc g++ build-essential libreadline-dev zlib1g-dev linux-headers-generic libssl-dev unzip -y
cd $home
systemctl enable nodews
systemctl start nodews
systemctl stop stunnel5
systemctl enable stunnel5
systemctl start stunnel5
systemctl restart stunnel5
x
rm -rf key.pem cert.pem sshjs
#/etc/init.d/dropbear restart
#/etc/init.d/stunnel4 restart
clear
