#!/bin/bash
country=ID
state=IDK
locality=IDK
organization=fas
organizationalunit=fas
commonname=fas
email=admin@fas.com

cd

#set time GMT +7 jakarta
#rm /etc/localtime
#ln -s /usr/share/zoneinfo/posix/Asia/Jakarta /etc/localtime

echo "=============== INSTALL UNTUK BUAT SSH ==============="
wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1unjHNf7PhWzq599fwoqY2g0PMnh4IkOz' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1unjHNf7PhWzq599fwoqY2g0PMnh4IkOz" -O /usr/bin/cek && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/cek

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1xltcIu-fdRiIofum6DQhD-dBgx1MGIOM' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xltcIu-fdRiIofum6DQhD-dBgx1MGIOM" -O /usr/bin/hapus && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/hapus

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1u4iRy52uBtrQ715wI3qC51bSDyzIgqaS' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1u4iRy52uBtrQ715wI3qC51bSDyzIgqaS" -O /usr/bin/list && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/list

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=10kp8lvRN_mFfHDF51Oh2ME58JvrWEl2a' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=10kp8lvRN_mFfHDF51Oh2ME58JvrWEl2a" -O /usr/bin/new && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/new

wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=d/1FUSVykTzJVHmEJgHvgTFrF1Tfa9j6tQu' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=d/1FUSVykTzJVHmEJgHvgTFrF1Tfa9j6tQu" -O /usr/bin/trial && rm -rf /tmp/cookies.txt
chmod +x /usr/bin/trial
clear

echo "=============== INSTALL STUNNEL4 ==============="
apt-get install stunnel4 -y
rm /etc/stunnel/stunnel.conf
cat > /etc/stunnel/stunnel.conf <<-END
pid = /var/run/stunnel.pid
cert = /etc/stunnel/stunnel.pem
client = no
socket = a:SO_REUSEADDR=1
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
[https]
accept = :::443
connect = :::80

END

echo "=============== INSTALL SERTIFIKAT ==============="
rm /etc/stunnel/stunnel.pem
openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 1095 \
					-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"
cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
clear

echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
clear

echo "=============== INSTALL WS ==============="

mkdir /etc/fas
wget -O /etc/fas/sh.py https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/sh.py
wget -O /etc/fas/fas.net https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/fas.net
chmod +x /etc/fas/fas.net
chmod +x /etc/fas/sh.js
clear

rm -rf /etc/systemd/system/nodews.service
cat > /etc/systemd/system/nodews.service <<-END
[Unit]
Description=fas-wsssl
After=network.target nss-lookup.target
[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/bin/python /etc/fas/sh.py 80
Restart=on-failure
RestartPreventExitStatus=1
[Install]
WantedBy=multi-user.target
END
clear

echo "=============== INSTALL BADVPN ==============="
wget -O /etc/fas/badvpn-udpgw https://github.com/gozhien/apa/raw/main/bad/badvpn-udpgw && chmod +x /etc/fas/badvpn-udpgw

cat > /etc/systemd/system/bad.service <<-END
[Unit]
Description=fas-bad
After=network.target nss-lookup.target
[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/etc/fas/badvpn-udpgw --listen-addr [::]:7300 --max-clients 1000 --max-connections-for-client 10
Restart=on-failure
RestartPreventExitStatus=1
[Install]
WantedBy=multi-user.target
END

systemctl enable bad
systemctl start bad
sed -i 's/127.0.0.1:222/127.0.0.1:22/' /etc/fas/sh.py

wget -O /usr/bin/x https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/gozhien/apa/main/x
chmod +x /usr/bin/x


echo "=============== MENJALANKAN SEMUA ==============="
cd $home
systemctl enable nodews
systemctl start nodews
x
rm -rf key.pem cert.pem open
clear
